name: Build Test

on:
  push:
    branches:   
    - '*'
    - '!main'
  pull_request:
    branches:
    - '*'
    - '!main'
    types:
    - open

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release
