name: Build Test

on:
  push:
    branches:   
    - '*'
    - '!main'
  pull_request:
    branches:
    - '*'
    - '!main'
    types:
    - open

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release

    
  #  strategy:
  #    matrix:
  #      dotnet-version: [8]

  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Use Node.js ${{ matrix.node-version }}
  #    uses: actions/setup-node@v3
  #    with:
  #      node-version: ${{ matrix.node-version }}
  #      cache: 'npm'
        
  #  - run: npm ci
  #  - run: npm run build --if-present
