name: Build Test Branches

on:
  push:
    branches:   
    - '*'
    - '!main'
  pull_request:
    branches:
    - '*'
    - '!main'
    types:
    - open

jobs:
  build:
    runs-on: ubuntu-latest
        
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Check if package-lock.json exists
    - name: Check for lock file
    - run: |
        if [ ! -f package-lock.json ]; then
          echo "Error: package-lock.json is missing.";
          exit 1;
        fi

    # Install dependencies using npm ci for CI/CD environments
    - name: Install dependencies
    - run: npm ci

    # Build the project if necessary
    - name: Build project
    - run: npm run build --if-present
