name: Angular Release Workflow

on:
  push:
    branches:  
    - 'add-new-release'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm ci

    - name: Get current version from package.json
      id: get_version
      run: |
        VERSION=$(jq -r .version package.json)
        echo "Current version is $VERSION TEST"
        echo "CURRENT_VERSION=$VERSION TEST" >> $GITHUB_ENV

    - name: Build Angular project
      run: |
        ng build --configuration production

    - name: Create Git tag with new version
      run: |
        git tag v$CURRENT_VERSION
        git push origin v$CURRENT_VERSION

    - name: Upload production build to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/{your-project-name}/**/*  # Adjust this path to match your dist folder
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
